CREATE TABLE IF NOT EXISTS `contacts` (
  `id`        	   INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user`		       INT(11) DEFAULT NULL,
  `type`		       VARCHAR(20) DEFAULT NULL,
  `value`		       VARCHAR(20) DEFAULT NULL,
  `preferred`	     BOOLEAN DEFAULT 0,
  `datecreated` 	 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `datemodified`   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `contacts` (`id`,`user`),
  FOREIGN KEY (user) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;