CREATE TABLE IF NOT EXISTS `users` (
  `id`        	   INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `firstname`		   VARCHAR(50) DEFAULT NULL,
  `lastname`		   VARCHAR(50) DEFAULT NULL,
  `title`	         VARCHAR(50) DEFAULT NULL,
  `gender`	       VARCHAR(1)  DEFAULT NULL,
  `dateofbirth`	   VARCHAR(10) DEFAULT NULL,
  `auth`	         JSON  DEFAULT NULL,
  `datecreated` 	 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `datemodified`   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;