version: '3.7'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    networks:
      - api
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_HOST: 127.0.0.1
      MYSQL_PASSWORD: demo
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: demo
    command: --default-authentication-plugin=mysql_native_password
  api:
    image: rmindo/python-api
    restart: always
    container_name: api
    ports:
      - 2000:80
    volumes:
      - ./:/www/api
    networks:
      - api
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_NAME: demo
      DB_PASSWORD: demo

networks:
  api:
    driver: bridge